import Providers from "@/components/Provider";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { getUser } from "@/lib/curruser";
import { Toaster } from "@/components/ui/toaster";
import { dashboardConfig } from "@/config/dashboard";
import { MainNav } from "./components/main-nav";
import UserAccountNav from "@/components/NavbarAccount";
import { DashboardNav } from "@/components/DashboardNav";
import { EdgeStoreProvider } from "@/lib/edgestore";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const user = await getUser()
  let adminPage = {}
  if(user?.emailAddresses[0].emailAddress === process.env.ADMIN_EMAIL || user?.emailAddresses[0].emailAddress === process.env.ADMIN_EMAIL2){

     adminPage = {
     title: "Upload Resource",
     href: "/dashboard/upload",
     icon: "post"
   }
  }

  let currentData = [...dashboardConfig.sidebarNav , adminPage]


  return (
    <html lang="en">
      <ClerkProvider>
        <Providers>
          <EdgeStoreProvider>
          <body className="min-h-screen ">
            <div className="flex min-h-screen flex-col space-y-6">
              <header className="sticky top-0 z-40 border-b bg-background">
                <div className="container flex h-16 items-center justify-between py-4">
                  <MainNav items={dashboardConfig.mainNav} />
                  {/* <Navbar /> */}
                  <div className="overflow-x-hidden sticky">
                    <UserAccountNav currentUser={user} />
                  </div>
                </div>
              </header>
              <div className="mt-96 max-w-8xl overflow-hidden flex mx-auto self-center items-center justify-center">
                {/* <Background /> */}
              </div>
              <div className="container grid flex-1 gap-12 md:grid-cols-[200px_1fr]">
                <aside className="hidden w-[200px] flex-col md:flex">
                  <DashboardNav items={currentData} user={user} />
                </aside>
                <main className="flex w-full flex-1 flex-col overflow-hidden">
                  {children}
                </main>
              </div>
              {/* <Footer /> */}
            </div>
          </body>


          </EdgeStoreProvider>
          <Toaster />
        </Providers>
      </ClerkProvider>
    </html>
  );
}
